'how to use:
'   CTRL+P -> "> PlantUML preview" 

@startuml test

Class SadConsole.Game{
    + Instance : SadConsole.Game

    + {static} void Create()
    + void Run()
    + void Dispose();

}

Class Game{
    

    + {static} void Setup()
    - void Init()
}

SadConsole.Game <|-- Game


@enduml